# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# title can include HTML code.
title: Little Stone
description: This is the site where Steven post his thoughts, ideas and feelings
author: Huan Li
language: en
timezone: Asia/Shanghai

# custom Site settings
SEOTitle: Little Stone - Huan Li's Blog
keyword: "Computer Science, Travel Notes, Ideas and Thoughts" # seo key words

# your favicon png
favicon: /blog/img/rockrms.png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://longaspire.github.io/blog
root: /blog/
# :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

footer:
# Specify the date when the site was setup.
# If not defined, current year will be used.
  since: 2018

  # Icon between year and copyright info.
  # From: http://fontawesome.io/
  # Example: user
  icon: user

  # If not defined, will be used `author` from Hexo main config.
  copyright: Huan Li. All rights reserved.
  # -------------------------------------------------------------
  # Hexo link (Powered by Hexo).
  powered: true
  # Theme & scheme info link (Theme - A-RSnippet).
  theme: false

  # -------------------------------------------------------------
  # Any custom text can be defined here.
  custom_text: Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a>

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: /
  about: /the-milestone-2018/
  categories: /categories/
  archives: /archives/
  tags: /tags/
#  RSS: /atom.xml

# ---------------------------------------------------------------
# Archive Generator
# ---------------------------------------------------------------
archive_generator:
  per_page: 6
  yearly: true
  monthly: false
  daily: false
  order_by: -date

# ---------------------------------------------------------------
# SNS settings
# ---------------------------------------------------------------
# Set rss to false to disable feed link.
# Leave url as empty to use site's feed link.
# Set url to specific value if you have burned your feed already.
rss:
  enable: false
#  url:                    # if empty, use default url, root_path/atom.xml

email: lihuancs@zju.edu.cn
# weibo_username:
# zhihu_username:
github_username: longaspire
twitter_username: LeeSte7en
facebook_username: stevenhuanlee
linkedin_username: lihuancs

# ---------------------------------------------------------------
# Sidebar settings
# ---------------------------------------------------------------
sidebar: false
#sidebar-about-description: # data scientist
#sidebar-avatar-url: # http://longaspire.com/avator.jpg

# ---------------------------------------------------------------
# Hexo official settings
# ---------------------------------------------------------------
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'unreleased/**'

# Writing: Defined by Hexo
new_post_name: :title.md                  # File name of new posts
default_layout: post
titlecase: false                          # Transform title into titlecase
external_link: true                       # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
#  tab_replace:

# Category & Tag
default_category: uncategorized
#category_map:
# tag_map:


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D, YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

## Themes: https://hexo.io/themes/
theme: huan

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/longaspire/blog.git
  branch: master


# ---------------------------------------------------------------
# Layout settings: homepage
# ---------------------------------------------------------------
# If enable, update date will show on the cover photo.
index_update_date_enable: true

# ---------------------------------------------------------------
# Layout settings: post layout & leetcode layout
# ---------------------------------------------------------------
# If enable, update date will show in the header.
post_update_date_enable: true

# Can contain HTML
# Appear at the begginning of the post
# content_before_post: <div class="subscribe"><a href="http://eepurl.com/dh6iCD" target="_blank">Get Updated for Each Release!</a></div><p>
# Can contain HTML
# Appear at the end of the post
# content_after_post: <a href="https://www.patreon.com/arsnippet" target="_blank"><img src="/img/patreon.png" alt="support my work at patron"></a> <a href="https://arsnippet.freeflarum.com/" target="_blank"><img src="/img/forum.jpg" alt="support my work at patron"></a> <a href="https://discord.gg/CB6CPzq" target="_blank"><img src="/img/discord.png" alt="Join the Discord"></a>

# default cover image
# example: animated gif as header
cover_default_img: /blog/img/northernlights-sisimiut-lake.jpg
brand_logo_img: /blog/img/banner.png?h=350&auto=compress&cs=tinysrgb


# Table Of Contents in the Sidebar
toc:
  enable: true
  # Automatically add list number to toc.
  number: true

# ---------------------------------------------------------------
# Layout settings: page layout
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Layout settings: archive layout
# ---------------------------------------------------------------
# archive page title
archive:
    title: Archives
    # subtitle: Cool?

# ---------------------------------------------------------------
# Layout settings: poem layout
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Layout settings: portfolio-slim layout
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Layout settings: 404 layout
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Layout settings: list-category-leetcode layout
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Layout settings: list-tag-leetcode layout
# ---------------------------------------------------------------

#################################################################
# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------
#################################################################
# MathJax Support
mathjax:
  enable: true
  # per_page: true
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# ---------------------------------------------------------------
# Comment settings
# ---------------------------------------------------------------
# Disqus settings
# disqus_shortname: hexo-a-rsnippet

# Use livere
use_livere: true
livere_uid: MTAyMC8zNjM1MC8xMjg4NQ

# ---------------------------------------------------------------
# Analytics settings
# ---------------------------------------------------------------
# Baidu Analytics
baidu_analytics: 13438f8a61802b465894989427ee4725
# Google Analytics
google_analytics: UA-118875263-1            # Format: UA-xxxxxx-xx
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
# Click "Alternative methods" => Select "HTML tag" => copy the string in the "content" property of "meta" element
# <meta name="google-site-verification" content="xxxxxx" />
# Input xxxxxx below
google_site_verification: Q9_p57DiEwLUAkG7RSWhWgytI3usFEsDzkR3UMn-RW8
#bing_site_verification:
#yandex_site_verification:

# ---------------------------------------------------------------
# Share
# ---------------------------------------------------------------
#add_this_id: # ra-5272bc2a7b3c1ddc
# Enable/Disable Update date

# ---------------------------------------------------------------
# Search
# ---------------------------------------------------------------
# search api , set your custom key
# It is not working now. It is a feature in the future.
# swiftype_key:

# ---------------------------------------------------------------
# hexo-image-caption add caption for iamges
# ---------------------------------------------------------------
image_caption:
  enable: true #false to disable
  class_name: 'image-caption-center' #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'

# ---------------------------------------------------------------
# Site Map
# ---------------------------------------------------------------
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# ---------------------------------------------------------------
# Code Highlight
# ---------------------------------------------------------------
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'solarizedlight'  #default, coy, dark, funky, okaidia, solarizedlight, tomorrow, twilight
  line_number: true     # default false
#  custom_css:        # optional

## ---------------------------------------------------------------
## Reference
## ---------------------------------------------------------------
#plugins:
#  - hexo-reference

# Theme version
version: 0.1.0
